In [1]:
import numpy as np
import plotly.graph_objects as go
import pandas as pd
from plotly.subplots import make_subplots

colors = {
    'AW': '#ef8a62',
    'MO': '#67a9cf',
    'MI': '#999999',
    'AW_2': '#613828'
}

In [5]:
offline_classification = pd.read_excel('classification_results/offline_classification_results.xlsx')
online_ov_classification = pd.read_excel('classification_results/online_overtime_classification_results.xlsx')
online_epoch_classification = pd.read_excel('classification_results/whole_epochs_classification_results.xlsx')

In [6]:
offline_classification

,Subject,Condition,Feature_Extraction,Accuracy,Selected_Features
0,1,AW,FBCSP,0.4125,"[6, 16, 10, 22, 19, 14, 12, 2, 20, 3]"
1,2,AW,FBCSP,0.5125,"[1, 6, 22, 4, 10, 16, 19, 12, 7, 14]"
2,3,AW,FBCSP,0.3750,"[18, 5, 13, 6, 19, 1, 15, 2, 11, 9]"
3,4,AW,FBCSP,0.5000,"[13, 3, 6, 2, 1, 18, 10, 5, 16, 9]"
4,5,AW,FBCSP,0.5375,"[18, 12, 6, 11, 8, 1, 16, 5, 20, 10]"
...,...,...,...,...,...
256,25,MI,Combined,0.7000,[]
257,26,MI,Combined,0.6875,[]
258,27,MI,Combined,0.6875,[]
259,28,MI,Combined,0.5375,[]
260,29,MI,Combined,0.6875,[]

In [7]:
online_ov_classification

,Subject,times,Condition,FBCSP_acc,FBCSP_std,ERP_acc,ERP_std,Combined_acc,Combined_std
0,1,1.248,AW_New,0.5,0.5,0.583333,0.493007,0.5,0.5
1,1,1.496,AW_New,0.5,0.5,0.666667,0.471405,0.5,0.5
2,1,1.744,AW_New,0.5,0.5,0.833333,0.372678,0.5,0.5
3,1,1.992,AW_New,0.5,0.5,0.750000,0.433013,0.5,0.5
4,1,2.240,AW_New,0.5,0.5,0.500000,0.500000,0.5,0.5
...,...,...,...,...,...,...,...,...,...
1095,29,2.736,MO,0.5,0.5,0.600000,0.489898,0.5,0.5
1096,29,2.984,MO,0.5,0.5,0.550000,0.497494,0.5,0.5
1097,29,3.232,MO,0.5,0.5,0.550000,0.497494,0.5,0.5
1098,29,3.480,MO,0.5,0.5,0.600000,0.489898,0.5,0.5
1099,29,3.728,MO,0.5,0.5,0.750000,0.433013,0.5,0.5

In [8]:
online_epoch_classification

     Subject Condition Feature_Extraction  Accuracy       Std
0          1    AW_New           Combined  0.500000  0.500000
1          1    AW_New              FBCSP  0.500000  0.500000
2          1    AW_New                ERP  0.583333  0.493007
3          3    AW_New           Combined  0.500000  0.500000
4          3    AW_New              FBCSP  0.500000  0.500000
..       ...       ...                ...       ...       ...
295       28        MO              FBCSP  0.500000  0.500000
296       28        MO                ERP  0.650000  0.476970
297       29        MO           Combined  0.500000  0.500000
298       29        MO              FBCSP  0.500000  0.500000
299       29        MO                ERP  0.550000  0.497494

[300 rows x 5 columns]

In [9]:
df

     Subject Condition  Accuracy Selected_Features
174        1        AW    0.6000                []
175        2        AW    0.4500                []
176        3        AW    0.6000                []
177        4        AW    0.6250                []
178        5        AW    0.4750                []
..       ...       ...       ...               ...
256       25        MI    0.7000                []
257       26        MI    0.6875                []
258       27        MI    0.6875                []
259       28        MI    0.5375                []
260       29        MI    0.6875                []

[87 rows x 4 columns]

In [10]:
df=offline_classification[offline_classification['Feature_Extraction']=='Combined'].drop(columns=['Feature_Extraction','Selected_Features'])
df_grouped = df.iloc[:,1:].groupby('Condition').agg(['mean', 'std'])
print(df_grouped)

# Calculate means and stds for error bars
means = df.groupby('Condition')['Accuracy'].mean()
stds = df.groupby('Condition')['Accuracy'].std()

# Create Plotly grouped bar chart with error bars
fig_combined = go.Figure()

for condition in df['Condition'].unique():
    cond_df = df[df['Condition'] == condition]
    fig_combined.add_trace(go.Bar(
        x=cond_df['Subject'],
        y=cond_df['Accuracy'],
        name=condition,
        marker_color=colors[condition],
        error_y=dict(
            type='data',
            array=[stds[condition]] * len(cond_df),  # same std for all bars in this condition
            visible=True,
            color ='rgba(0,0,0,0.5)'

        )
    ))

# Add chance level line
fig_combined.add_hline(y=0.5, line_width=1, line_color="gray")

# Update layout to show subject IDs on x-axis ticks
fig_combined.update_layout(
    barmode='group',
    xaxis_title='Subject',
    yaxis_title='Accuracy',
    title='Accuracy per Subject and Condition  - Combined FBCSP and ERP',
    legend_title_text='Condition',
    xaxis=dict(
        tickmode='array',
        tickvals=offline_classification['Subject'].unique(),
        ticktext=offline_classification['Subject'].unique()
    ),
    yaxis=dict(range=[0.3, 1.0], tick0=0.4, dtick=0.1),
)

fig_combined.show()

           Accuracy
               mean       std
Condition
AW         0.583190  0.076348
MI         0.605603  0.089179
MO         0.605172  0.089050

In [11]:
df=offline_classification[offline_classification['Feature_Extraction']=='FBCSP'].drop(columns=['Feature_Extraction','Selected_Features'])

df_grouped = df.iloc[:,1:].groupby('Condition').agg(['mean', 'std'])
print(df_grouped)

# Calculate means and stds for error bars
means = df.groupby('Condition')['Accuracy'].mean()
stds = df.groupby('Condition')['Accuracy'].std()

# Create Plotly grouped bar chart with error bars
fig_FBCSP = go.Figure()

for condition in df['Condition'].unique():
    cond_df = df[df['Condition'] == condition]
    fig_FBCSP.add_trace(go.Bar(
        x=cond_df['Subject'],
        y=cond_df['Accuracy'],
        name=condition,
        marker_color=colors[condition],
        error_y=dict(
            type='data',
            array=[stds[condition]] * len(cond_df),  # same std for all bars in this condition
            visible=True,
            color ='rgba(0,0,0,0.5)'

        )
    ))

# Add chance level line
fig_FBCSP.add_hline(y=0.5, line_width=1, line_color="gray")

# Update layout to show subject IDs on x-axis ticks
fig_FBCSP.update_layout(
    barmode='group',
    xaxis_title='Subject',
    yaxis_title='Accuracy',
    title='Accuracy per Subject and Condition  -  FBCSP',
    legend_title_text='Condition',
    xaxis=dict(
        tickmode='array',
        tickvals=df['Subject'].unique(),
        ticktext=df['Subject'].unique()
    ),
    yaxis=dict(range=[0.0, 1.0], tick0=0.4, dtick=0.1),
)

fig_FBCSP.show()

           Accuracy
               mean       std
Condition
AW         0.501724  0.070134
MI         0.540517  0.060748
MO         0.507328  0.072235

In [12]:
df=offline_classification[offline_classification['Feature_Extraction']=='ERP'].drop(columns=['Feature_Extraction','Selected_Features'])

df_grouped = df.iloc[:,1:].groupby('Condition').agg(['mean', 'std'])
print(df_grouped)

# Calculate means and stds for error bars
means = df.groupby('Condition')['Accuracy'].mean()
stds = df.groupby('Condition')['Accuracy'].std()

# Create Plotly grouped bar chart with error bars
fig_ERP = go.Figure()

for condition in df['Condition'].unique():
    cond_df = df[df['Condition'] == condition]
    fig_ERP.add_trace(go.Bar(
        x=cond_df['Subject'],
        y=cond_df['Accuracy'],
        name=condition,
        marker_color=colors[condition],
        error_y=dict(
            type='data',
            array=[stds[condition]] * len(cond_df),  # same std for all bars in this condition
            visible=True,
            color ='rgba(0,0,0,0.5)'
        )
    ))

# Add chance level line
fig_ERP.add_hline(y=0.5, line_width=1, line_color="gray")

# Update layout to show subject IDs on x-axis ticks
fig_ERP.update_layout(
    barmode='group',
    xaxis_title='Subject',
    yaxis_title='Accuracy',
    title='Accuracy per Subject and Condition  - ERP',
    legend_title_text='Condition',
    xaxis=dict(
        tickmode='array',
        tickvals=df['Subject'].unique(),
        ticktext=df['Subject'].unique()
    ),
    yaxis=dict(range=[0, 1.0], tick0=0, dtick=0.25),
)

fig_ERP.show()

           Accuracy
               mean       std
Condition
AW         0.497845  0.064958
MI         0.521121  0.058354
MO         0.503879  0.051224

In [28]:

fig = make_subplots(
    rows=3, cols=1,
    #specs=[[{"colspan": 2}, None],
    #       [{}, {}]],
    subplot_titles=("Combined FBCSP and ERP", "FBCSP", "ERP"),
    vertical_spacing=0.08,
)
for trace in fig_combined.data:
	fig.add_trace(trace, row=1, col=1)
for trace in fig_FBCSP.data:
	fig.add_trace(trace, row=2, col=1)
for trace in fig_ERP.data:
	fig.add_trace(trace, row=3, col=1,
)

fig.add_hline(y=0.5, line_width=1, line_color="gray", row=1, col=1)
fig.update_yaxes(range=[0, 1.0], tick0=0, dtick=0.25, row=1, col=1, title='Accuracy')
fig.update_xaxes(tickmode='array', tickvals=df['Subject'].unique(), ticktext=df['Subject'].unique(), row=1, col=1)
fig.add_hline(y=0.5, line_width=1, line_color="gray", row=2, col=1)
fig.update_yaxes(range=[0.0, 1.0], tick0=0, dtick=0.25, row=2, col=1)
fig.update_xaxes(tickmode='array', tickvals=df['Subject'].unique(), ticktext=df['Subject'].unique(), row=2, col=1)
fig.add_hline(y=0.5, line_width=1, line_color="gray", row=3, col=1)
fig.update_yaxes(range=[0, 1.0], tick0=0, dtick=0.25, row=3, col=1)
fig.update_xaxes(tickmode='array', tickvals=df['Subject'].unique(), ticktext=df['Subject'].unique(), row=3, col=1)
fig.update_xaxes(title_text='Subject', row=3, col=1)
fig.update_layout(
    height=800, width=1200,
    legend_title_text='Condition',
    barmode='group',
    template="simple_white"
)


for j, trace in enumerate(fig.data):
    if j >2:
        trace.showlegend = False

fig.show()

In [107]:
online_ov_classification.groupby('Condition').agg(['mean']).drop(columns=['Subject', 'times'])

          FBCSP_acc FBCSP_std   ERP_acc   ERP_std Combined_acc Combined_std
               mean      mean      mean      mean         mean         mean
Condition
AW_New     0.494242  0.494735  0.532121  0.476274     0.496970     0.489923
AW_Seen    0.491364  0.488963  0.539545  0.464721     0.492273     0.470440
MI         0.512000  0.496127  0.504364  0.489033     0.502909     0.496005
MO         0.511273  0.496692  0.496545  0.487317     0.510545     0.495957

In [172]:
fig_AW_seen = go.Figure()
fig_AW_new = go.Figure()
fig_MI = go.Figure()
fig_MO = go.Figure()


x_times = np.linspace(0,2.5,11)*1000  # Convert to milliseconds
all_online_AW_results_seen=online_ov_classification[online_ov_classification['Condition']=='AW_Seen']
all_online_AW_results_new=online_ov_classification[online_ov_classification['Condition']=='AW_New']
all_online_MI_results=online_ov_classification[online_ov_classification['Condition']=='MI']
all_online_MO_results=online_ov_classification[online_ov_classification['Condition']=='MO']

# Seen AW
plot_data_aw_seen = {}
plot_data_aw_new = {}
plot_data_MI = {}
plot_data_MO = {}

for subject in all_online_AW_results_seen.Subject.unique():

    fbcsp_mean = np.mean(all_online_AW_results_seen[all_online_AW_results_seen['Subject']==subject]['FBCSP_acc'])
    erp_mean = np.mean(all_online_AW_results_seen[all_online_AW_results_seen['Subject']==subject]['ERP_acc'])
    combined_mean = np.mean(all_online_AW_results_seen[all_online_AW_results_seen['Subject']==subject]['Combined_acc'])
    means = {'FBCSP': fbcsp_mean, 'ERP': erp_mean, 'Combined': combined_mean}
    best_model_name = max(means, key=means.get)
    plot_data_aw_seen[subject] = {
        'model_name': best_model_name,
        'accuracies': all_online_AW_results_seen[all_online_AW_results_seen['Subject']==subject][f'{best_model_name}_acc'].tolist()
    }


    fbcsp_mean = np.mean(all_online_AW_results_new[all_online_AW_results_new['Subject']==subject]['FBCSP_acc'])
    erp_mean = np.mean(all_online_AW_results_new[all_online_AW_results_new['Subject']==subject]['ERP_acc'])
    combined_mean = np.mean(all_online_AW_results_new[all_online_AW_results_new['Subject']==subject]['Combined_acc'])
    means = {'FBCSP': fbcsp_mean, 'ERP': erp_mean, 'Combined': combined_mean}
    best_model_name = max(means, key=means.get)
    plot_data_aw_new[subject] = {
        'model_name': best_model_name,
        'accuracies': all_online_AW_results_new[all_online_AW_results_new['Subject']==subject][f'{best_model_name}_acc'].tolist()
    }

    fbcsp_mean = np.mean(all_online_MI_results[all_online_MI_results['Subject']==subject]['FBCSP_acc'])
    erp_mean = np.mean(all_online_MI_results[all_online_MI_results['Subject']==subject]['ERP_acc'])
    combined_mean = np.mean(all_online_MI_results[all_online_MI_results['Subject']==subject]['Combined_acc'])
    means = {'FBCSP': fbcsp_mean, 'ERP': erp_mean, 'Combined': combined_mean}
    best_model_name = max(means, key=means.get)
    plot_data_MI[subject] = {
        'model_name': best_model_name,
        'accuracies': all_online_MI_results[all_online_MI_results['Subject']==subject][f'{best_model_name}_acc'].tolist()
    }

    fbcsp_mean = np.mean(all_online_MO_results[all_online_MO_results['Subject']==subject]['FBCSP_acc'])
    erp_mean = np.mean(all_online_MO_results[all_online_MO_results['Subject']==subject]['ERP_acc'])
    combined_mean = np.mean(all_online_MO_results[all_online_MO_results['Subject']==subject]['Combined_acc'])
    means = {'FBCSP': fbcsp_mean, 'ERP': erp_mean, 'Combined': combined_mean}
    best_model_name = max(means, key=means.get)
    plot_data_MO[subject] = {
        'model_name': best_model_name,
        'accuracies': all_online_MO_results[all_online_MO_results['Subject']==subject][f'{best_model_name}_acc'].tolist()
    }
# Sort subjects numerically
sorted_subjects = sorted(plot_data_aw_seen.keys(), key=lambda x: int(x))
y_subjects = [f"{subject}: {plot_data_aw_seen[subject]['model_name']}" for subject in sorted_subjects]
z_accuracies = [plot_data_aw_seen[subject]['accuracies'] for subject in sorted_subjects]
fig_AW_seen.add_trace(go.Heatmap(
    x=x_times,
    y=y_subjects,
    z=z_accuracies,
    text=z_accuracies,
    texttemplate="%{z:.2f}",
    colorscale=[[0.0, 'red'], [0.5, 'white'], [1.0, 'blue']],
    zmin=0,
    zmax=1,
    colorbar=dict(title="Accuracy"),
))

sorted_subjects = sorted(plot_data_aw_new.keys(), key=lambda x: int(x))
y_subjects = [f"{subject}: {plot_data_aw_new[subject]['model_name']}" for subject in sorted_subjects]
z_accuracies = [plot_data_aw_new[subject]['accuracies'] for subject in sorted_subjects]
fig_AW_new.add_trace(go.Heatmap(
    x=x_times,
    y=y_subjects,
    z=z_accuracies,
    text=z_accuracies,
    texttemplate="%{z:.2f}",
    colorscale=[[0.0, 'red'], [0.5, 'white'], [1.0, 'blue']],
    zmin=0,
    zmax=1,
    colorbar=dict(title="Accuracy"),
))

sorted_subjects = sorted(plot_data_MI.keys(), key=lambda x: int(x))
y_subjects = [f"{subject}: {plot_data_MI[subject]['model_name']}" for subject in sorted_subjects]
z_accuracies = [plot_data_MI[subject]['accuracies'] for subject in sorted_subjects]
fig_MI.add_trace(go.Heatmap(
    x=x_times,
    y=y_subjects,
    z=z_accuracies,
    text=z_accuracies,
    texttemplate="%{z:.2f}",
    colorscale=[[0.0, 'red'], [0.5, 'white'], [1.0, 'blue']],
    zmin=0,
    zmax=1,
    colorbar=dict(title="Accuracy"),
))


sorted_subjects = sorted(plot_data_MO.keys(), key=lambda x: int(x))
y_subjects = [f"{subject}: {plot_data_MO[subject]['model_name']}" for subject in sorted_subjects]
z_accuracies = [plot_data_MO[subject]['accuracies'] for subject in sorted_subjects]
fig_MO.add_trace(go.Heatmap(
    x=x_times,
    y=y_subjects,
    z=z_accuracies,
    text=z_accuracies,
    texttemplate="%{z:.2f}",
    colorscale=[[0.0, 'red'], [0.5, 'white'], [1.0, 'blue']],
    zmin=0,
    zmax=1,
    colorbar=dict(title="Accuracy"),
))

print('done')

done

In [173]:
fig_AW_seen.update_layout( xaxis_tickmode='linear',xaxis_dtick=250,
                      height=1000, width=1600)
fig_AW_seen.show()

In [171]:
fig_AW_new.update_layout( xaxis_tickmode='linear',xaxis_dtick=250,
                      height=1000, width=1600)
fig_AW_new.show()

In [174]:
fig_MO.update_layout( xaxis_tickmode='linear',xaxis_dtick=250,
                      height=1000, width=1600)
fig_MO.show()

In [175]:
fig_MI.update_layout( xaxis_tickmode='linear',xaxis_dtick=250,
                      height=1000, width=1600)
fig_MI.show()

In [176]:
fig = make_subplots(rows=2, cols=2, subplot_titles=("MI", "MO", "Seen AW", "New AW"), vertical_spacing=0.07, horizontal_spacing=0.08)

for trace in fig_MI.data:
    fig.add_trace(trace, row=1, col=1)
for trace in fig_MO.data:
    fig.add_trace(trace, row=1, col=2)
for trace in fig_AW_seen.data:
    fig.add_trace(trace, row=2, col=1)
for trace in fig_AW_new.data:
    fig.add_trace(trace, row=2, col=2)

fig.update_yaxes(autorange='reversed', row=1, col=1)
fig.update_yaxes(autorange='reversed', row=1, col=2)
fig.update_yaxes(autorange='reversed', row=2, col=1)
fig.update_yaxes(autorange='reversed', row=2, col=2)

fig.update_layout(
    xaxis_tickmode='linear',
    xaxis_dtick=250,
    xaxis2_dtick=250,
    xaxis3_dtick=250,
    xaxis4_dtick=250,
    height=1000, width=1600,
    xaxis4_title='Time (ms)',
)
fig.add_annotation(
    yref="paper",
    yanchor="bottom",
    y=1.01,  

    text="#Subject: best model",

    xref="paper",
    xanchor="center",
    x=-0.020,

    showarrow=False,
    font=dict(size=12)
    )
fig.show()

In [133]:
def plot_data_to_df(plot_data, condition):
    rows = []
    for subject, info in plot_data.items():
        accs = np.array(info['accuracies'])
        rows.append({
            'Subject': subject,
            'Condition': condition,
            'Model': info['model_name'],
            'Mean_Accuracy': np.mean(accs),
            'Std_Accuracy': np.std(accs)
        })
    return pd.DataFrame(rows)

df_aw_seen = plot_data_to_df(plot_data_aw_seen, 'AW_Seen')
df_aw_new = plot_data_to_df(plot_data_aw_new, 'AW_New')
df_mi = plot_data_to_df(plot_data_MI, 'MI')
df_mo = plot_data_to_df(plot_data_MO, 'MO')

df_unique = pd.concat([df_aw_seen, df_aw_new, df_mi, df_mo], ignore_index=True)
df_unique.groupby(['Condition']).agg(['mean']).drop(columns=['Subject'])

          Mean_Accuracy Std_Accuracy
                   mean         mean
Condition
AW_New         0.557576     0.074548
AW_Seen        0.588636     0.093646
MI             0.544909     0.053514
MO             0.541455     0.048554

In [177]:
df_aw_seen

    Subject Condition     Model  Mean_Accuracy  Std_Accuracy
0         1   AW_Seen       ERP       0.715909      0.141932
1         3   AW_Seen       ERP       0.693182      0.123441
2         4   AW_Seen     FBCSP       0.534091      0.077072
3         5   AW_Seen     FBCSP       0.500000      0.000000
4         6   AW_Seen     FBCSP       0.500000      0.000000
5         7   AW_Seen       ERP       0.579545      0.096424
6         8   AW_Seen       ERP       0.579545      0.096424
7         9   AW_Seen       ERP       0.556818      0.154144
8        10   AW_Seen  Combined       0.659091      0.107805
9        11   AW_Seen       ERP       0.670455      0.060131
10       12   AW_Seen  Combined       0.579545      0.110175
11       13   AW_Seen       ERP       0.511364      0.195507
12       14   AW_Seen  Combined       0.522727      0.071870
13       15   AW_Seen       ERP       0.545455      0.122390
14       16   AW_Seen  Combined       0.659091      0.160706
15       17   AW_Seen       ERP       0.727273      0.139176
16       18   AW_Seen  Combined       0.727273      0.071870
17       19   AW_Seen     FBCSP       0.500000      0.000000
18       20   AW_Seen     FBCSP       0.443182      0.097754
19       21   AW_Seen       ERP       0.625000      0.176777
20       22   AW_Seen  Combined       0.704545      0.080353
21       24   AW_Seen       ERP       0.659091      0.185335
22       25   AW_Seen       ERP       0.511364      0.035935
23       28   AW_Seen  Combined       0.511364      0.035935
24       29   AW_Seen     FBCSP       0.500000      0.000000

In [127]:
df_aw_new

    Subject Condition     Model  Mean_Accuracy  Std_Accuracy
0         1    AW_New       ERP       0.606061  1.333850e-01
1         3    AW_New  Combined       0.500000  0.000000e+00
2         4    AW_New       ERP       0.560606  8.769573e-02
3         5    AW_New     FBCSP       0.500000  0.000000e+00
4         6    AW_New     FBCSP       0.530303  4.008714e-02
5         7    AW_New  Combined       0.530303  8.159341e-02
6         8    AW_New       ERP       0.537879  1.027626e-01
7         9    AW_New  Combined       0.507576  2.395665e-02
8        10    AW_New       ERP       0.606061  5.138129e-02
9        11    AW_New       ERP       0.583333  1.110223e-16
10       12    AW_New  Combined       0.696970  1.138886e-01
11       13    AW_New       ERP       0.530303  1.138886e-01
12       14    AW_New       ERP       0.681818  1.457226e-01
13       15    AW_New       ERP       0.590909  1.350951e-01
14       16    AW_New       ERP       0.560606  9.462118e-02
15       17    AW_New       ERP       0.643939  1.128762e-01
16       18    AW_New       ERP       0.522727  1.183371e-01
17       19    AW_New       ERP       0.530303  1.082035e-01
18       20    AW_New       ERP       0.613636  1.922512e-01
19       21    AW_New     FBCSP       0.500000  0.000000e+00
20       22    AW_New     FBCSP       0.431818  6.943297e-02
21       24    AW_New     FBCSP       0.500000  0.000000e+00
22       25    AW_New  Combined       0.553030  6.428243e-02
23       28    AW_New       ERP       0.621212  7.422696e-02
24       29    AW_New     FBCSP       0.500000  0.000000e+00

In [128]:
df_mi

    Subject Condition     Model  Mean_Accuracy  Std_Accuracy
0         1        MI       ERP       0.545455      0.081057
1         3        MI     FBCSP       0.595455      0.058210
2         4        MI     FBCSP       0.500000      0.000000
3         5        MI     FBCSP       0.518182      0.032141
4         6        MI     FBCSP       0.513636      0.030829
5         7        MI  Combined       0.509091      0.035791
6         8        MI     FBCSP       0.440909      0.092486
7         9        MI     FBCSP       0.586364      0.052617
8        10        MI  Combined       0.527273      0.044536
9        11        MI       ERP       0.554545      0.103253
10       12        MI       ERP       0.581818      0.064922
11       13        MI     FBCSP       0.500000      0.000000
12       14        MI       ERP       0.572727      0.103053
13       15        MI     FBCSP       0.527273      0.024896
14       16        MI       ERP       0.527273      0.068635
15       17        MI     FBCSP       0.509091      0.019285
16       18        MI       ERP       0.554545      0.096424
17       19        MI     FBCSP       0.618182      0.032141
18       20        MI       ERP       0.650000      0.092932
19       21        MI       ERP       0.577273      0.061658
20       22        MI  Combined       0.545455      0.058210
21       24        MI     FBCSP       0.486364      0.043122
22       25        MI     FBCSP       0.581818      0.044070
23       28        MI  Combined       0.500000      0.030151
24       29        MI     FBCSP       0.600000      0.067420

In [130]:
df_mo

    Subject Condition     Model  Mean_Accuracy  Std_Accuracy
0         1        MO     FBCSP       0.495455      0.014374
1         3        MO       ERP       0.527273      0.071870
2         4        MO       ERP       0.550000      0.067420
3         5        MO     FBCSP       0.500000      0.000000
4         6        MO       ERP       0.531818      0.109280
5         7        MO     FBCSP       0.627273      0.083567
6         8        MO     FBCSP       0.586364      0.030829
7         9        MO       ERP       0.577273      0.044536
8        10        MO     FBCSP       0.563636      0.064282
9        11        MO       ERP       0.545455      0.039626
10       12        MO     FBCSP       0.500000      0.000000
11       13        MO       ERP       0.454545      0.107565
12       14        MO     FBCSP       0.522727      0.049376
13       15        MO       ERP       0.595455      0.065555
14       16        MO     FBCSP       0.586364      0.074134
15       17        MO     FBCSP       0.495455      0.014374
16       18        MO  Combined       0.500000      0.000000
17       19        MO       ERP       0.522727      0.117480
18       20        MO     FBCSP       0.500000      0.000000
19       21        MO  Combined       0.504545      0.025713
20       22        MO     FBCSP       0.509091      0.019285
21       24        MO     FBCSP       0.559091      0.041660
22       25        MO  Combined       0.595455      0.033402
23       28        MO  Combined       0.581818      0.061322
24       29        MO       ERP       0.604545      0.078203